import { PHONE_EVENTS_IOS } from './ios';
import { PHONE_EVENTS_ANDROID } from './android';

export const PHONE_EVENTS = {
  DEVICE_RATIO_CHANGE: 'DEVICE_RATIO_CHANGE',
  SIGNAL_STRENGTH_CHANGE_IOS: 'SIGNAL_STRENGTH_CHANGE_IOS',
  CARRIER_CHANGE: 'CARRIER_CHANGE',
  SIGNAL_TYPE_CHANGE: 'SIGNAL_TYPE_CHANGE',
  HOUR_CHANGE: 'HOUR_CHANGE',
  MINUTE_CHANGE: 'MINUTE_CHANGE',
  BATTERY_CHANGE: 'BATTERY_CHANGE',
  BATTERY_STATUS_CHANGE: 'BATTERY_STATUS_CHANGE',
  SHOW_BATTERY_PERCENTAGE_CHANGE: 'SHOW_BATTERY_PERCENTAGE_CHANGE',

  ...PHONE_EVENTS_IOS,
  ...PHONE_EVENTS_ANDROID,
};
