import { PHONE_EVENTS_IOS } from './ios';
import { PHONE_EVENTS_ANDROID } from './android';

export const PHONE_EVENTS = {
  SIGNAL_STRENGTH_CHANGE_IOS: 'SIGNAL_STRENGTH_CHANGE_IOS',
  CARRIER_CHANGE: 'CARRIER_CHANGE',
  SIGNAL_TYPE_CHANGE: 'SIGNAL_TYPE_CHANGE',
  HOUR_CHANGE: 'HOUR_CHANGE',
  MINUTE_CHANGE: 'MINUTE_CHANGE',
  BATTERY_CHANGE: 'BATTERY_CHANGE',
  BATTERY_STATUS_CHANGE: 'BATTERY_STATUS_CHANGE',
  SHOW_BATTERY_PERCENTAGE_CHANGE: 'SHOW_BATTERY_PERCENTAGE_CHANGE',
  CHAT_TYPE_CHANGE: 'CHAT_TYPE_CHANGE',
  MEMBER_COUNT_CHANGE: 'MEMBER_COUNT_CHANGE',
  CHAT_TITLE_CHANGE: 'CHAT_TITLE_CHANGE',
  UNREAD_COUNT: 'UNREAD_COUNT',

  ...PHONE_EVENTS_IOS,
  ...PHONE_EVENTS_ANDROID,
};
