export default {
  CHAT_TYPE_CHANGE: 'CHAT_TYPE_CHANGE',
  MEMBER_COUNT_CHANGE: 'MEMBER_COUNT_CHANGE',
  CHAT_TITLE_CHANGE: 'CHAT_TITLE_CHANGE',
  UNREAD_COUNT: 'UNREAD_COUNT',
  UPDATE_MESSAGE: 'UPDATE_MESSAGE',
  SHOW_USER_NAME: 'SHOW_USER_NAME',
  BG_IMAGE: 'BG_IMAGE',
  PREVIEW: 'PREVIEW',
};
