export default {
  UPDATE_TYPE: 'UPDATE_TYPE',
  UPDATE_AVATAR: 'UPDATE_AVATAR',
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
  UPDATE_STATUS: 'UPDATE_STATUS',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_TRANSFER_TIME: 'UPDATE_TRANSFER_TIME',
  UPDATE_RECEIVE_TIME: 'UPDATE_RECEIVE_TIME',
  UPDATE_PAY_METHOD: 'UPDATE_PAY_METHOD',
  UPDATE_BILL_NUMBER: 'UPDATE_BILL_NUMBER'
}
