import { CATEGORY, COLOR, THEME } from './base';

const TOOL_CONVERTOR_ID = {
  NUMERAL_SYSTEM: 'numeral-system',
  TEXT_BINARY: 'text-binary',
  TEXT_DECIMAL: 'text-decimal',
  TEXT_HEX: 'text-hex',
  LENGTH_UNIT: 'length-unit',
  TIME_UNIT: 'time-unit',
  CASE: 'case',
  COLOR: 'color',
};

export const CONVERTOR = [
  {
    id: TOOL_CONVERTOR_ID.NUMERAL_SYSTEM,
    text: 'Numeral System',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'convertor',
    color: COLOR.ORANGE,
    iconTheme: THEME.ORANGE,
    description: 'numeralSystemDesc',
  },
  {
    id: TOOL_CONVERTOR_ID.TEXT_BINARY,
    text: 'Text-Binary',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'text',
    color: COLOR.YELLOW,
    iconTheme: THEME.YELLOW,
    description: 'textBinaryDesc',
  },
  {
    id: TOOL_CONVERTOR_ID.TEXT_DECIMAL,
    text: 'Text-Decimal',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'text',
    color: COLOR.RED,
    iconTheme: THEME.RED,
    description: 'textDecimalDesc',
  },
  {
    id: TOOL_CONVERTOR_ID.TEXT_HEX,
    text: 'Text-Hex',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'text',
    color: COLOR.GREEN,
    iconTheme: THEME.GREEN,
    description: 'textHexDesc',
  },
  // TODO
  // {
  //   id: 'domain-ip',
  //   text: 'Domain to IP',
  //   category: CATEGORY.CONVERTOR,
  //   categoryId: CATEGORY.CONVERTOR,
  //   icon: 'ip-domain',
  //   color: COLOR.WATHET,
  //   iconTheme: THEME.WATHET,
  //   isWIP: true,
  // },
  {
    id: TOOL_CONVERTOR_ID.LENGTH_UNIT,
    text: 'Length Unit Convertor',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'length-unit',
    color: COLOR.ORANGE,
    iconTheme: THEME.ORANGE,
    description: 'lengthUnitDesc',
  },
  {
    id: TOOL_CONVERTOR_ID.TIME_UNIT,
    text: 'Time Unit Convertor',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'time-unit',
    color: COLOR.GREEN,
    iconTheme: THEME.GREEN,
    description: 'timeUnitDesc',
  },
  {
    id: TOOL_CONVERTOR_ID.CASE,
    text: 'Case Convertor',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'case',
    color: COLOR.BLUE,
    iconTheme: THEME.BLUE,
    description: 'caseConvertorDesc',
  },
  {
    id: TOOL_CONVERTOR_ID.COLOR,
    text: 'Color Convertor',
    category: CATEGORY.CONVERTOR,
    categoryId: CATEGORY.CONVERTOR,
    icon: 'palette',
    color: COLOR.WATHET,
    iconTheme: THEME.WATHET,
    description: 'colorConvertorDesc', // TODO
  },
];
