import { CATEGORY, COLOR, THEME } from './base';

const TOOL_TIMER_ID = {
  COUNTDOWN: 'countdown',
  COUNT_TIMER: 'count-timer',
  ONLINE_CLOCK: 'online-clock',
  WORLD_CLOCK: 'world-clock',
  TIMESTAMP: 'timestamp',
  CHRONOGRAPH: 'chronograph',
  ALARM: 'alarm',
};

export const TIMER = [
  {
    id: TOOL_TIMER_ID.COUNTDOWN,
    text: 'Countdown',
    category: CATEGORY.TIMER,
    categoryId: CATEGORY.TIMER,
    icon: 'countdown',
    color: COLOR.RED,
    iconTheme: THEME.RED,
    description: 'countdownDesc',
  },
  {
    id: TOOL_TIMER_ID.COUNT_TIMER,
    text: 'Count Timer',
    category: CATEGORY.TIMER,
    categoryId: CATEGORY.TIMER,
    icon: 'count-timer',
    color: COLOR.ORANGE,
    iconTheme: THEME.ORANGE,
    description: 'countTimerDesc',
  },
  {
    id: TOOL_TIMER_ID.ONLINE_CLOCK,
    text: 'Online Clock',
    category: CATEGORY.TIMER,
    categoryId: CATEGORY.TIMER,
    icon: 'clock',
    color: COLOR.GREEN,
    iconTheme: THEME.GREEN,
    description: 'onlineClockDesc',
  },
  // TODO
  // {
  //   id: TOOL_TIMER_ID.WORLD_CLOCK,
  //   text: 'World Clock',
  //   category: CATEGORY.TIMER,
  //   categoryId: CATEGORY.TIMER,
  //   icon: 'world-clock',
  //   color: COLOR.YELLOW,
  //   iconTheme: THEME.YELLOW,
  //   isWIP: true,
  // },
  {
    id: TOOL_TIMER_ID.TIMESTAMP,
    text: 'TimeStamp',
    category: CATEGORY.TIMER,
    categoryId: CATEGORY.TIMER,
    icon: 'timestamp',
    color: COLOR.WATHET,
    iconTheme: THEME.WATHET,
    description: 'timeStampDesc',
  },
  {
    id: TOOL_TIMER_ID.CHRONOGRAPH,
    text: 'Chronograph',
    category: CATEGORY.TIMER,
    categoryId: CATEGORY.TIMER,
    icon: 'chronograph',
    color: COLOR.PURPLE,
    iconTheme: THEME.PURPLE,
    description: 'chronographDesc',
  },
  {
    id: TOOL_TIMER_ID.ALARM,
    text: 'Alarm Clock',
    category: CATEGORY.TIMER,
    categoryId: CATEGORY.TIMER,
    icon: 'alarm',
    color: COLOR.BLUE,
    iconTheme: THEME.BLUE,
    description: 'alarmClockDesc',
  },
];
